from tkinter import*
window=Tk()
window.title("Application")
window.geometry("400x400")
window.configure(background="#22C5CF")
label1=Label(window,text="Welcome to myApp", fg="red",height=2,width=20)
button1=Button(window,text="click here",fg="#CF2286",bg="red",height=2,width=10)
label2=Label(window,text="Welcome to menu", fg="blue",height=2,width=20)
button2=Button(window,text="click here",fg="#CF2286",bg="green",height=2,width=10)
label3=Label(window,text="settings", fg="green",height=2,width=20)
button3=Button(window,text="click here",fg="#CF2286",bg="brown",height=2,width=10)
label1.pack()
button1.pack()
label2.pack()
button2.pack()
label3.pack()
button3.pack()
window.mainloop()